"use client";
import { useState } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TopFrame from "@/components/my_ui/topframe";
import "./globals.css";
import Homeui from "@/components/my_ui/Home";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const pagesMap: Record<string, React.ReactNode> = {
  "/": <Homeui />
};
function renderContent(route: string) {
  if (pagesMap[route]) return pagesMap[route];
  // If route is a URL, render in iframe
  if (route.startsWith("http")) {
    return <iframe src={route} className="w-full h-full border-none" />;
  }
  return <div>Page not found</div>;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [activeRoute, setActiveRoute] = useState("/");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen w-screen overflow-hidden flex flex-col">
          <TopFrame onTabChangeAction={setActiveRoute} />
          <main className="flex-1 overflow-auto pt-[48px]">
            {renderContent(activeRoute)}
          </main>
        </div>
      </body>
    </html>
  );
}